// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhF7c56GQIlLFDlUpKeXxlorbJC3YNmXE',
    appId: '1:952824095296:web:2d59c659cf37913fc1f5a5',
    messagingSenderId: '952824095296',
    projectId: 'virelon-game',
    authDomain: 'virelon-game.firebaseapp.com',
    storageBucket: 'virelon-game.firebasestorage.app',
    measurementId: 'G-5WCMM9WN03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNQLGZlgoah4nVQrMQVAlvPTajPNyT-MY',
    appId: '1:952824095296:android:326ab655f87fe20ec1f5a5',
    messagingSenderId: '952824095296',
    projectId: 'virelon-game',
    storageBucket: 'virelon-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhI3VGZZDQHbKNJQBEhtFcH9n20v77cvQ',
    appId: '1:952824095296:ios:3ecd09ef77c5fb27c1f5a5',
    messagingSenderId: '952824095296',
    projectId: 'virelon-game',
    storageBucket: 'virelon-game.firebasestorage.app',
    iosBundleId: 'com.example.virelon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhI3VGZZDQHbKNJQBEhtFcH9n20v77cvQ',
    appId: '1:952824095296:ios:3ecd09ef77c5fb27c1f5a5',
    messagingSenderId: '952824095296',
    projectId: 'virelon-game',
    storageBucket: 'virelon-game.firebasestorage.app',
    iosBundleId: 'com.example.virelon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhF7c56GQIlLFDlUpKeXxlorbJC3YNmXE',
    appId: '1:952824095296:web:04c8cdb43c840bbfc1f5a5',
    messagingSenderId: '952824095296',
    projectId: 'virelon-game',
    authDomain: 'virelon-game.firebaseapp.com',
    storageBucket: 'virelon-game.firebasestorage.app',
    measurementId: 'G-7186895VLY',
  );
}
